version: "3"

grpc:
  listen: "tcp://0.0.0.0:9001"
  proto: ./proto/ping.proto
  workers:
    command: "php src/server.php"
    pool:
      numWorkers: 4


logs:
  level: debug
  mode: development
  channels:
    http:
      level: info
    grpc:
      level: debug