<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto

namespace GPBMetadata;

class Ping
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a93010a0a70696e672e70726f746f120470696e67221e0a0b50696e6752657175657374120f0a076d657373616765180120012809221c0a0950696e675265706c79120f0a076d65737361676518012001280932390a0b50696e6753657276696365122a0a0450696e6712112e70696e672e50696e67526571756573741a0f2e70696e672e50696e675265706c79620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

